import { BadgeCheck, Code2, ExternalLink, ShieldCheck, XCircle } from 'lucide-react';

import { Button } from '@/components/ui/button';
import type { InvoiceRecord, SiteSettings } from '@/lib/types';

export function VerificationView({ data }: { data: { invoice: InvoiceRecord; settings: SiteSettings } | null }) {
  if (!data) return <main className="verify-shell grid min-h-screen place-items-center px-5"><section className="verify-card text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-red-400/10 text-red-300"><XCircle className="size-8"/></span><h1 className="mt-5 text-2xl font-black text-white">تعذر التحقق</h1><p className="mt-2 leading-7 text-slate-400">الفاتورة غير موجودة أو أن رابط التحقق غير صحيح.</p></section></main>;
  const { invoice, settings } = data; return <main className="verify-shell grid min-h-screen place-items-center px-5 py-12"><section className="verify-card"><div className="flex items-center gap-3"><span className="brand-mark"><Code2/></span><div><strong className="text-white">{settings.brand_name}</strong><span className="block text-[10px] text-cyan-300/70">OFFICIAL VERIFICATION</span></div></div><span className={`mx-auto mt-9 grid size-20 place-items-center rounded-[26px] ${invoice.status==='issued'?'bg-emerald-400/10 text-emerald-300':'bg-red-400/10 text-red-300'}`}>{invoice.status==='issued'?<BadgeCheck className="size-10"/>:<XCircle className="size-10"/>}</span><div className="mt-6 text-center"><p className="text-xs font-bold text-cyan-300">نتيجة التحقق</p><h1 className="mt-2 text-3xl font-black text-white">{invoice.status==='issued'?'فاتورة صحيحة وفعّالة':'فاتورة ملغاة'}</h1><p className="mx-auto mt-3 max-w-md leading-7 text-slate-400">{settings.verification_message}</p></div><div className="mt-7 grid gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-5 sm:grid-cols-2"><div><span className="text-xs text-slate-500">رقم الفاتورة</span><strong dir="ltr" className="mt-1 block text-right font-mono text-cyan-200">{invoice.invoice_number}</strong></div><div><span className="text-xs text-slate-500">تاريخ الإصدار</span><strong className="mt-1 block text-white">{new Date(invoice.issued_at).toLocaleDateString('ar-EG')}</strong></div><div><span className="text-xs text-slate-500">اسم المستلم</span><strong className="mt-1 block text-white">{invoice.recipient_name}</strong></div><div><span className="text-xs text-slate-500">القيمة</span><strong className="mt-1 block text-white">{Number(invoice.amount).toLocaleString('ar-EG')} ج.م</strong></div></div>{settings.verification_link&&<Button className="submit-button mt-5 h-11 w-full" render={<a aria-label="فتح الرابط الإضافي" href={settings.verification_link} target="_blank" rel="noreferrer">معرفة المزيد</a>}><ExternalLink/> معرفة المزيد</Button>}<p className="mt-5 flex items-center justify-center gap-2 text-center text-xs text-slate-500"><ShieldCheck className="size-4"/> تم التحقق مباشرة من سجل Muhkam Academy</p></section></main>;
}
